# Generated by Django 2.2.2 on 2019-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloga', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='spaday.jpg', upload_to=''),
        ),
    ]
